- link:
    ~/.tmux.conf: ui/tmux/tmux.conf
    ~/.tmux.conf.local: ui/tmux/tmux.conf.local

- shell:
    # clone TPM tmux plugin manager
  - [git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm, cloning Tmux Plugin Manager]
    # install the plugins
  - [bash ~/.tmux/plugins/tpm/bin/install_plugins, Installing Tmux Plugins]
