{
  description = "A Modern Nix-based Dotfiles Flake";

  # --- Inputs ---
  # All inputs pin to the same nixpkgs to avoid duplicate dependencies.
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    darwin = {
      # nix-darwin: macOS system configuration (like NixOS but for Mac)
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    determinate = {
      # Determinate Systems Nix installer and settings manager
      url = "https://flakehub.com/f/DeterminateSystems/determinate/3";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nix-system-graphics = {
      # GPU/graphics support for non-NixOS Linux systems
      url = "github:soupglasses/nix-system-graphics";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    zen-browser = {
      # Zen Browser — not yet in nixpkgs
      url = "github:youwen5/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, darwin, determinate, zen-browser, ... }@inputs:
    let
      # username is defined in vars.nix (gitignored, generated by apply.sh)
      vars = import ./vars.nix;
      username = vars.username;

      # mkHome: standalone home-manager for non-NixOS Linux systems (e.g. Kali)
      # Usage: mkHome "x86_64-linux" [ ./home/linux.nix ]
      mkHome = system: extraModules: home-manager.lib.homeManagerConfiguration {
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        modules = [
          ./home  # shared base config (home/default.nix)
        ] ++ extraModules;
        extraSpecialArgs = { inherit system username; };
      };

      # mkNixos: full NixOS system config with home-manager integrated as a module
      # Usage: mkNixos "x86_64-linux"
      # Home config: home/default.nix + home/linux-common.nix
      mkNixos = system: nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs username; };
        modules = [
          ./hosts/nixos/configuration.nix
          home-manager.nixosModules.home-manager
          {
            nixpkgs.config.allowUnfree = true;
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.${username} = { imports = [ ./home ./home/linux-common.nix ]; };
            home-manager.extraSpecialArgs = { inherit system username; isNixOS = true; };
          }
        ];
      };

      # mkDarwin: nix-darwin system config with home-manager integrated
      # Usage: mkDarwin "aarch64-darwin"
      # Home config: home/darwin.nix (which imports home/default.nix)
      mkDarwin = system: darwin.lib.darwinSystem {
        inherit system;
        modules = [
          determinate.darwinModules.default
          ./hosts/darwin/configuration.nix
          home-manager.darwinModules.home-manager
          {
            nixpkgs.config.allowUnfree = true;
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.${username} = import ./home/darwin.nix;
            home-manager.extraSpecialArgs = { inherit system username; };
          }
        ];
        specialArgs = { inherit self username inputs; };
      };
    in {
      # Determinate Systems Nix daemon settings (applies on all platforms)
      determinate = {
        customSettings = {
          experimental-features = "nix-command flakes";
          extra-experimental-features = "parallel-eval";
          lazy-trees = true;
          eval-cores = 0; # use all cores for parallel evaluation
          warn-dirty = false;
        };
      };

      # Standalone home-manager configs (non-NixOS Linux)
      homeConfigurations."linux" = mkHome "x86_64-linux" [ ./home/linux.nix ];
      homeConfigurations."kali"  = mkHome "x86_64-linux" [ ./home/linux.nix ./home/kali.nix ];

      # NixOS system configs — hostname must match nixosConfigurations key
      nixosConfigurations."codelab-nix" = mkNixos "x86_64-linux";

      # macOS system configs
      darwinConfigurations."mac-arm"   = mkDarwin "aarch64-darwin";
      darwinConfigurations."mac-intel" = mkDarwin "x86_64-darwin";

      # Dev shell for applying nix-darwin configs (macOS only)
      devShells = let
        mkDevShell = system: let
          pkgs = import nixpkgs { inherit system; };
          darwinConfig = if system == "aarch64-darwin" then "mac-arm" else "mac-intel";
        in {
          default = pkgs.mkShellNoCC {
            packages = with pkgs; [
              (writeShellApplication {
                name = "apply-nix-darwin-configuration";
                runtimeInputs = [ inputs.darwin.packages.${system}.darwin-rebuild ];
                text = ''
                  echo "> Applying nix-darwin configuration..."
                  echo "> Running darwin-rebuild switch as root..."
                  sudo darwin-rebuild switch --flake ".#${darwinConfig}"
                  echo "> darwin-rebuild switch was successful"
                  echo "> macOS config was successfully applied"
                '';
              })
            ];
          };
        };
      in {
        "x86_64-darwin"  = mkDevShell "x86_64-darwin";
        "aarch64-darwin" = mkDevShell "aarch64-darwin";
      };
    };
}
