{
  description = "A Modern Nix-based Dotfiles Flake";

  # --- Inputs ---
  # All inputs pin to the same nixpkgs to avoid duplicate dependencies.
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixpkgs-yabai.url = "github:nixos/nixpkgs/e6f23dc08d3624daab7094b701aa3954923c6bbb";
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    darwin = {
      # nix-darwin: macOS system configuration (like NixOS but for Mac)
      url = "github:LnL7/nix-darwin";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    determinate = {
      url = "https://flakehub.com/f/DeterminateSystems/determinate/3";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    zen-browser = {
      # Zen Browser — not yet in nixpkgs
      url = "github:youwen5/zen-browser-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, home-manager, darwin, determinate, ... }@inputs:
    let
      # Username from vars.nix (generated by apply.sh before running sudo)
      vars = import ./vars.nix;
      username = vars.username;

      # mkHome: standalone home-manager for non-NixOS Linux systems (e.g. Kali)
      # Usage: mkHome "x86_64-linux" [ ./home/linux.nix ]
      mkHome = system: extraModules: home-manager.lib.homeManagerConfiguration {
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        modules = [
          ./home  # shared base config (home/default.nix)
        ] ++ extraModules;
        extraSpecialArgs = { inherit system username inputs; isNixOS = false; isServer = false; };
      };

      # mkServer: same as mkHome but passes isServer = true to suppress all GUI packages/programs.
      # Usage: mkServer "x86_64-linux" true/false  (isNixOS)
      mkServer = system: isNixOS: home-manager.lib.homeManagerConfiguration {
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };
        modules = [ ./home ];
        extraSpecialArgs = { inherit system username inputs isNixOS; isServer = true; };
      };

      # mkNixos: full NixOS system config with home-manager integrated as a module
      # Usage: mkNixos "x86_64-linux" []
      # Home config: home/default.nix + home/linux.nix
      mkNixos = system: extraModules: nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = { inherit inputs username; };
        modules = [
          ./hosts/nixos/configuration.nix
          home-manager.nixosModules.home-manager
          {
            nixpkgs.config.allowUnfree = true;
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.${username} = { imports = [ ./home ./home/linux.nix ]; };
            home-manager.extraSpecialArgs = { inherit system username inputs; isNixOS = true; isServer = false; };
          }
        ] ++ extraModules;
      };

      # mkDarwin: nix-darwin system config with home-manager integrated
      # Usage: mkDarwin "aarch64-darwin"
      # Home config: home/darwin.nix (which imports home/default.nix)
      mkDarwin = system: darwin.lib.darwinSystem {
        inherit system;
        modules = [
          determinate.darwinModules.default
          ./hosts/darwin/configuration.nix
          home-manager.darwinModules.home-manager
          {
            nixpkgs.config.allowUnfree = true;
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.${username} = import ./home/darwin.nix;
            home-manager.extraSpecialArgs = { inherit system username inputs; isServer = false; };
          }
        ];
        specialArgs = { inherit self username inputs; };
      };
    in {
      # Determinate Systems Nix daemon settings (applies on all platforms)
      determinate = {
        customSettings = {
          experimental-features = "nix-command flakes";
          extra-experimental-features = "parallel-eval";
          lazy-trees = true;
          eval-cores = 0; # use all cores for parallel evaluation
          warn-dirty = false;
          min-free = 10737418240;  # 10GB - trigger GC during builds when below this
          max-free = 32212254720;  # 30GB - stop GC when this much is free
        };
      };

      # Standalone home-manager configs (x86_64 Linux only — aarch64 Linux unsupported)
      homeConfigurations."linux"  = mkHome "x86_64-linux" [ ./home/linux.nix ];
      homeConfigurations."kali"   = mkHome "x86_64-linux" [ ./home/linux.nix ./home/kali.nix ];
      homeConfigurations."server"       = mkServer "x86_64-linux" false;
      homeConfigurations."server-nixos" = mkServer "x86_64-linux" true;

      # NixOS system configs — hostname must match nixosConfigurations key
      nixosConfigurations."codelab-nix" = mkNixos "x86_64-linux" [];

      # QEMU VM for testing dotfiles — run with:
      #   nix build .#nixosConfigurations.vm.config.system.build.vm && ./result/bin/run-nixos-vm
      nixosConfigurations."vm" = mkNixos "x86_64-linux" [
        {
          virtualisation.vmVariant = {
            virtualisation.memorySize = 4096;
            virtualisation.cores = 3;
            virtualisation.graphics = true;
          };
          # Simple password for VM login — not for production use
          users.users.${username}.initialPassword = "test";  # pragma: allowlist secret
        }
      ];

      # macOS system configs
      darwinConfigurations."mac-arm"   = mkDarwin "aarch64-darwin";
      darwinConfigurations."mac-intel" = mkDarwin "x86_64-darwin";
    };
}
