#!/usr/bin/env bash

# Exit on error, undefined variables, and pipe failures
set -euo pipefail

# --- Color Definitions ---
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]] || [[ "${1:-}" == "-n" ]]; then
    DRY_RUN=true
    echo -e "${YELLOW}==> DRY RUN MODE: No files will be deleted.${NC}"
fi

echo -e "${BLUE}==>${NC} Starting Uninstallation of Dotfiles..."

# Function to remove a path with dry-run support
remove_path() {
    local path="$1"
    if [ -e "$path" ] || [ -L "$path" ]; then
        if [ "$DRY_RUN" = true ]; then
            echo "Would remove: $path"
        else
            echo "Removing: $path"
            rm -rf "$path"
        fi
    fi
}

# 1. Remove Home Manager activation lock and profile
echo -e "${BLUE}==>${NC} Cleaning up Home Manager profiles..."
remove_path "$HOME/.nix-profile"
remove_path "$HOME/.home-manager-activation-lock"

# 2. Remove configuration files generated by Nix/Home-Manager
echo -e "${BLUE}==>${NC} Cleaning up local Nix state and config..."
remove_path "$HOME/.config/nix"
remove_path "$HOME/.config/nixpkgs"
remove_path "$HOME/.cache/nix"
remove_path "$HOME/.local/state/nix"

# 3. Remove the local private vars.nix bridge
echo -e "${BLUE}==>${NC} Cleaning up local flake variables..."
remove_path "$(dirname "$0")/vars.nix"

# 4. Attempt to remove Home Manager managed symlinks in HOME
# This is tricky without the list, but we can target common areas
echo -e "${BLUE}==>${NC} Cleaning up common symlink targets..."
# (This section could be expanded if a specific list of managed files is known)

if [ "$DRY_RUN" = false ]; then
    echo -e "${GREEN}==>${NC} Uninstallation complete!"
    if [ -x "/nix/nix-installer" ]; then
        echo -e "${BLUE}==>${NC} Running Determinate Nix Uninstaller..."
        /nix/nix-installer uninstall
    else
        echo -e "${YELLOW}Note:${NC} /nix/nix-installer not found. Use standard uninstall procedures if needed."
    fi
else
    echo -e "${BLUE}==>${NC} Dry run complete. No changes were made."
fi
