
# === General exports
export EDITOR="nvim"
export TERM="xterm-256color"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# === oh-my-zsh
export ZSH="$HOME/.oh-my-zsh"
# Themes = agnoster, abaykan
ZSH_THEME="powerlevel10k/powerlevel10k"
DISABLE_UNTRACKED_FILES_DIRTY="true"
DISABLE_UPDATE_PROMPT="true"
DISABLE_AUTO_UPDATE="true"
HIST_STAMPS="%d/%m/%y %T"

plugins=(
    git
    vi-mode
    autojump
    archlinux
    colored-man-pages
    zsh-autosuggestions
    zsh-syntax-highlighting
)


# === Extra files to be sourced
source $ZSH/oh-my-zsh.sh
source ~/.aliases
source ~/.functionsrc
source ~/.dockerrc
source ~/.gitrc
source ~/.pythonrc
file_source ~/.secrets
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
file_source ~/.p10k.zsh


# === History related options
export HISTSIZE=999999999
# amount of history to keep in memory
export SAVEHIST=999999999
# amount of history to save
setopt hist_ignore_all_dups
# ignore all the duplicated command consecutively
setopt hist_ignore_space
# ignore the history items starting with space
setopt hist_expire_dups_first
# expire duplicates when trimming history
unsetopt share_history
# disable shared history for multiple zsh sessions

# === OS related configs
if [ "$(uname -s)" = "Darwin" ]; then
    source ~/.macrc
elif [ "$(uname -s)" = "Linux" ]; then
    source ~/.linuxrc
fi

# --- McFly's configuration
export MCFLY_FUZZY=2
export MCFLY_DISABLE_MENU=FALSE
export MCFLY_KEY_SCHEME=vim
eval "$(mcfly init zsh)"
