# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

export EDITOR="vim"
export LANG="en_US.UTF-8"

 #Themes = agnoster, abaykan
ZSH_THEME="agnoster"
DISABLE_UNTRACKED_FILES_DIRTY="true"
DISABLE_UPDATE_PROMPT="true"
HIST_STAMPS="mm/dd/yyyy"

plugins=(
  autojump
  vi-mode
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  colored-man-pages
)

function file_source() {
    # check file exists and source
    # parameter 1: the file name
    [ -f $1 ] && source $1
}

if [ -f /etc/os-release ]; then
    ARCH=$(cat /etc/os-release | grep 'ID_LIKE' | cut -d'=' -f2)
    if [ ! -z $ARCH ]; then
        # linux only
        source ~/.archlinuxrc
    fi
fi

source $ZSH/oh-my-zsh.sh
source ~/.aliases
source ~/.functionsrc
source ~/.dockerrc
source ~/.gitrc
source ~/.pythonrc

file_source ~/.secrets
file_source ~/.fzf.zsh
unsetopt share_history
